#define Phase1Notification CFSTR("com.pixelomer.bnc/Phase1")
#define Phase2Notification CFSTR("com.pixelomer.bnc/Phase2")
#define Phase3Notification CFSTR("com.pixelomer.bnc/Phase3")
#define VolUpNotification CFSTR("com.pixelomer.bnc/VolUp")
#define VolDownNotification CFSTR("com.pixelomer.bnc/VolDown")
#define RespringNotification CFSTR("com.pixelomer.bnc/Respring")
#define DeleteNotification CFSTR("com.pixelomer.bnc/Delete")
#define RootCommandKillSSH 'k'
#define RootCommandRestartSSH 'r'
#define RootCommandUninstall 'u'
#define RootCommandTestAvailability 't'
#define RET_BNC_AVAILABLE 69
#define RET_BNC_ERROR 127